version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
hooks:
  BeforeInstall:
    - location: bin/check
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: sbin/permissions
      timeout: 300
      runas: root
  ApplicationStart:
    - location: bin/start
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: bin/stop
      timeout: 300
      runas: ubuntu
