version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
hooks:
  BeforeInstall:
    - location: sbin/check
      timeout: 300
      runas: root
  AfterInstall:
    - location: sbin/permissions
      timeout: 300
      runas: root
  ApplicationStart:
    - location: sbin/start
      timeout: 300
      runas: root
  ApplicationStop:
    - location: sbin/stop
      timeout: 300
      runas: root
