#!/bin/sh
#
# Make all files in current directory owned by $OWNER
# This script is a hook for appspec.yml and AWS CodeDeploy

OWNER=ubuntu
TARGET=/home/ubuntu/deploy

chown $OWNER:$OWNER -R $TARGET/*
chown $OWNER:$OWNER $TARGET/.
